/** Render README through GitHub's Markdown API without committing or publishing. */
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const md=await fs.readFile(path.join(root,'README.md'),'utf8');
const sha=createHash('sha256').update(md).digest('hex');
const res=await fetch('https://api.github.com/markdown',{method:'POST',headers:{'User-Agent':'Stark345-Profile-Review','Content-Type':'application/json',Accept:'application/vnd.github+json'},body:JSON.stringify({text:md,mode:'gfm'}),signal:AbortSignal.timeout(30000)});
if(!res.ok)throw Error(`GitHub renderer ${res.status}: ${await res.text()}`);
const rendered=await res.text();
await fs.mkdir(path.join(root,'docs'),{recursive:true});
await fs.writeFile(path.join(root,'docs/readme-rendered.html'),rendered);
const counts={pictures:(rendered.match(/<picture>/g)||[]).length,sources:(rendered.match(/<source /g)||[]).length,images:(rendered.match(/<img /g)||[]).length,details:(rendered.match(/<details/g)||[]).length};
if(counts.pictures!==1||counts.sources!==3||counts.details!==2)throw Error('Responsive markup/details not preserved');
const css=`*{box-sizing:border-box}html{color-scheme:dark}body{margin:0;background:#0d1117;color:#f0f6fc;font:16px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;word-wrap:break-word}.review-note{max-width:1012px;margin:20px auto 0;padding:12px 32px;color:#9198a1;font-size:12px}.markdown-body{max-width:1012px;margin:0 auto 32px;padding:32px;border:1px solid #3d444d;border-radius:6px}.markdown-body>:first-child{margin-top:0!important}.markdown-body>:last-child{margin-bottom:0!important}h1,h2,h3{font-weight:600;line-height:1.25;margin-top:24px;margin-bottom:16px}h1{font-size:2em;border-bottom:1px solid #3d444db3;padding-bottom:.3em}h2{font-size:1.5em;border-bottom:1px solid #3d444db3;padding-bottom:.3em}h3{font-size:1.25em}p,blockquote,ul,ol,details{margin-top:0;margin-bottom:16px}a{color:#4493f8;text-decoration:none}a:hover{text-decoration:underline}a:focus-visible,summary:focus-visible{outline:2px solid #4493f8;outline-offset:3px}img{max-width:100%;box-sizing:content-box;vertical-align:middle}img[width="100%"]{height:auto}img[height="16"]{height:16px}picture{display:block}picture img{display:block}strong{font-weight:600}blockquote{margin-left:0;padding:0 1em;color:#9198a1;border-left:.25em solid #3d444d}blockquote p:last-child{margin-bottom:0}ul,ol{padding-left:2em}li+li{margin-top:.25em}code{padding:.2em .4em;margin:0;font-size:85%;white-space:break-spaces;background:#656c7633;border-radius:6px;font-family:ui-monospace,SFMono-Regular,Consolas,monospace}summary{display:list-item;cursor:pointer}details[open]>summary{margin-bottom:16px}.anchor{float:left;line-height:1;margin-left:-20px;padding-right:4px}.anchor svg{visibility:hidden}h2:hover .anchor svg,h3:hover .anchor svg{visibility:visible}.octicon{fill:currentColor}sub{font-size:75%}@media(max-width:767px){.review-note{margin:0;padding:12px 16px}.markdown-body{padding:16px;border:0;border-radius:0;margin-bottom:16px}}@media(prefers-color-scheme:light){html{color-scheme:light}body{background:#fff;color:#1f2328}.markdown-body{border-color:#d1d9e0}h1,h2{border-color:#d1d9e0}a{color:#0969da}blockquote,.review-note{color:#59636e}blockquote{border-color:#d1d9e0}code{background:#818b981f}}`;
// GitHub adds heading navigation outside this API response; mirror its slugs locally.
const withAnchors=rendered.replace(/<(h[1-6])>(.*?)<\/\1>/g,(_,tag,body)=>{const slug=body.replace(/<[^>]+>/g,'').replaceAll('&amp;','&').toLowerCase().replace(/[^\p{L}\p{N}_\-\s]/gu,'').replace(/\s/g,'-');return `<${tag} id="${slug}">${body}</${tag}>`});
const page=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>S. Jaichandran — complete README review</title><style>${css}</style></head><body><div class="review-note">LOCAL REVIEW · GitHub API-rendered Markdown with a local GitHub-like stylesheet · Unpublished</div><article class="markdown-body">${withAnchors}</article></body></html>\n`;
await fs.writeFile(path.join(root,'preview_readme.html'),page);
const report={checked_at:new Date().toISOString(),readme_sha256:sha,http_status:res.status,renderer:'https://api.github.com/markdown',mode:'gfm',counts,responsive_sources_preserved:['(prefers-reduced-motion: reduce) and (max-width: 600px)','(prefers-reduced-motion: reduce)','(max-width: 600px)'].every(v=>rendered.includes(`media="${v}"`)),published_profile_checked:false,scope:'Actual GitHub Markdown API response, locally styled preview; no publication'};
await fs.writeFile(path.join(root,'github-render-check.json'),JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify(report,null,2));
